### ISSUE TITLE
DiffModel Experminet 1 - UNet - Gradient Descent - L2 - MNIST

### ISSUE THREAD

**Issue by mbaddar1** [mbaddar1/genmodel#14]
This is a preliminary experiment of the experiment set document in sec 8.7.1 here
https://github.com/mbaddar1/phd_latex/blob/c37daefa57518c5d4fa762a7cb254f1cbaa5c617/out/main.pdf 
___
**Experiment objectives** : 
1. Get hands on with DDPM  PyTorch Repo  https://github.com/mbaddar1/denoising-diffusion-pytorch 

2. Understand the UNet architecture 

3. Understand the DDPM L2 loss function

4. Plot the evolution of evaluation metric and loss function 

**Conduct an experiment as follows**

_Dataset :_ 
for test : 
1 ) mvn 2d as in my test code here 
https://github.com/mbaddar1/genmodel/blob/master/sandbox/diffmodel/simple_diffusion_model.py#L33
and also similar to this mvn experiment here
https://github.com/mbaddar1/genmodel/commit/dff602646af6f8663e21074add5e0f2c8b7aae3b 
In the old experiment the code was using KL divergence and some different head and time variant tail as model, instead of UNet
In this experiment : we will use UNet and DDPM L2. Both will use Gradient Descent 

https://scikit-learn.org/stable/modules/generated/sklearn.datasets.make_swiss_roll.html
 ___

2 ) Circles
https://scikit-learn.org/stable/modules/generated/sklearn.datasets.make_circles.html 

similar to the previous experiment 

https://github.com/mbaddar1/genmodel/commit/f82e3f099e5ce0181be83c630b9f8dc989b06814 

_Model_ 
Use UNet model as in this code part
https://github.com/mbaddar1/denoising-diffusion-pytorch/blob/main/denoising_diffusion_pytorch/denoising_diffusion_pytorch.py#L272 
___

_Loss function_ 
Use the L2 Loss as in 
https://arxiv.org/pdf/2006.11239.pdf eq 14 p5

_Optimization Method_
Gradient Descent as in 
https://arxiv.org/pdf/2006.11239.pdf  Algorithm 1 P4

___

_Evaluation Metric_ 
FID as in Fig 3 and 4 in    https://arxiv.org/pdf/2006.11239.pdf

**Comment by mbaddar1** [comment]
At the line
denoising-diffusion-pytorch/denoising_diffusion_pytorch/denoising_diffusion_pytorch.py:920

        self.ds = Dataset(folder, self.image_size, augment_horizontal_flip = augment_horizontal_flip, convert_image_to = convert_image_to)

something is wrong when loading images, all of then are zeros which lead to nan loss. Need to test a simple separate loader 
https://pytorch.org/tutorials/beginner/basics/data_tutorial.html

**Comment by mbaddar1** [comment]
Still having the nan loss issue
/home/mbaddar/Documents/mbaddar/phd/genmodel/genmodel39_venv/bin/python /home/mbaddar/Documents/mbaddar/phd/genmodel/sandbox/diffmodel/ddpm_torch_test.py 
INFO:root:Is cuda available ? : True
INFO:root:Cuda device count = 1
INFO:root:Creating Unet model:
Non-A100 GPU detected, using math or mem efficient attention if input tensor is on cuda
INFO:root:If core model is on cuda ? : True
INFO:root:Is diffusion model on cuda? : True
loss: nan:   0%|          | 431/700000 [10:17<278:28:35,  1.43s/it]
Traceback (most recent call last):
  File "/home/mbaddar/Documents/mbaddar/phd/genmodel/sandbox/diffmodel/ddpm_torch_test.py", line 89, in <module>
    trainer.train()
  File "/home/mbaddar/Documents/mbaddar/phd/genmodel/denoising-diffusion-pytorch/denoising_diffusion_pytorch/denoising_diffusion_pytorch.py", line 1107, in train
    total_loss += loss.item()
KeyboardInterrupt



Found that between these two checkpoints, x becomes nan
https://github.com/mbaddar1/denoising-diffusion-pytorch/commit/ce7b83bc15fcd016db6cb72c1bc9d03b05b015ab#diff-1ef0846017d5c27bd277b66e5afcab8798667afd39675e6f9382fc7e87a1fe28R444

Next step : try to understand why and fixed it by experimenting different dataset or normlization

**Comment by mbaddar1** [comment]
Started an isolated debug experience to address the nan loss issue with mnist dataset
https://github.com/mbaddar1/denoising-diffusion-pytorch/commit/152120513bbeb029bf99b9ff51c28f662bb839a5

Finding : for the isolated debugging script 
https://github.com/mbaddar1/denoising-diffusion-pytorch/commit/152120513bbeb029bf99b9ff51c28f662bb839a5#diff-1afb8a607120d6ec85007618cada69715241a0dea3e33b4ffc9a0c441d241ed4
The output of this line (the loss)
https://github.com/mbaddar1/denoising-diffusion-pytorch/commit/152120513bbeb029bf99b9ff51c28f662bb839a5#diff-1afb8a607120d6ec85007618cada69715241a0dea3e33b4ffc9a0c441d241ed4R55
is not nan
while still in this line
https://github.com/mbaddar1/denoising-diffusion-pytorch/commit/152120513bbeb029bf99b9ff51c28f662bb839a5
is still nan whilch leads to nan loss

next steps
1) maybe torch data type
2) maybe it is good to write a small trainer 
3) test with normlize and normalize in this line
https://github.com/mbaddar1/denoising-diffusion-pytorch/commit/152120513bbeb029bf99b9ff51c28f662bb839a5#diff-1ef0846017d5c27bd277b66e5afcab8798667afd39675e6f9382fc7e87a1fe28R863
4) also remove adhoc debug code, use only log debug

**Comment by mbaddar1** [comment]
Created a new trainer class to get hands on DiffModel
https://github.com/mbaddar1/denoising-diffusion-pytorch/commit/48a22864820737ccaaf41b77230911e68a99d6d9
not tested yet

**Comment by mbaddar1** [comment]
Build and tested a DDPM model , GradDesc , L2 loss , for MNIST num 8 dataset
https://github.com/mbaddar1/denoising-diffusion-pytorch/commit/2c86262dae0175c891a17c6cab891a435b466bc4
The generated images are here
denoising_diffusion_pytorch/ddpm_sandbox/generated_img_*.png

**Comment by mbaddar1** [comment]
Ticket finished and PR merged
https://github.com/mbaddar1/denoising-diffusion-pytorch/pull/2

**Comment by mbaddar1** [comment]
After discussion with Martin he agreed on the baseline experiment setup and the rest of the direction
