### ISSUE TITLE
Revisit Sinkhorn Evaluation 

### ISSUE THREAD

**Issue by mbaddar1** [mbaddar1/genmodel#21]
**GeomLoss**
Referring to #18 , try GeomLoss sinkhorn and fix the CUDA problem

```
/home/mbaddar/Documents/mbaddar/phd/genmodel/genmodel39_venv/bin/python /home/mbaddar/Documents/mbaddar/phd/genmodel/denoising-diffusion-pytorch/stat_dist/test_sinkhorn.py 
[KeOps] Compiling cuda jit compiler engine ... 
[KeOps] Warning : There were warnings or errors compiling formula :
/usr/bin/ld: cannot find -lnvrtc: No such file or directory
collect2: error: ld returned 1 exit status

OK
[pyKeOps] Compiling nvrtc binder for python ... 
[KeOps] Warning : There were warnings or errors compiling formula :
/usr/bin/ld: cannot find -lnvrtc: No such file or directory
collect2: error: ld returned 1 exit status

OK
/home/mbaddar/Documents/mbaddar/phd/genmodel/denoising-diffusion-pytorch/stat_dist/test_sinkhorn.py:20: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd
INFO:root:Testing sinkhorn with sklearn circles dataset
INFO:root:calculating sinkhorn distance with dataset pairs : sklearn_circles_same_params
INFO:root:Starting sinkhorn calculations
Traceback (most recent call last):
  File "/home/mbaddar/Documents/mbaddar/phd/genmodel/denoising-diffusion-pytorch/stat_dist/test_sinkhorn.py", line 96, in <module>
    sh_dist = sinkhorn_wrapper(X1=val["X1"], X2=val["X2"])
  File "/home/mbaddar/Documents/mbaddar/phd/genmodel/denoising-diffusion-pytorch/stat_dist/test_sinkhorn.py", line 34, in sinkhorn_wrapper
    dist = loss(X1, X2).item()
  File "/home/mbaddar/Documents/mbaddar/phd/genmodel/genmodel39_venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/mbaddar/Documents/mbaddar/phd/genmodel/genmodel39_venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/mbaddar/Documents/mbaddar/phd/genmodel/genmodel39_venv/lib/python3.9/site-packages/geomloss/samples_loss.py", line 265, in forward
    values = routines[self.loss][backend](
  File "/home/mbaddar/Documents/mbaddar/phd/genmodel/genmodel39_venv/lib/python3.9/site-packages/geomloss/kernel_samples.py", line 128, in kernel_loss
    a_x = (K_xx @ α.detach().unsqueeze(-1)).squeeze(-1)
  File "/home/mbaddar/Documents/mbaddar/phd/genmodel/genmodel39_venv/lib/python3.9/site-packages/pykeops/common/lazy_tensor.py", line 2308, in __matmul__
    Kv = Kv.sum(Kv.dim() - 2, **kwargs)  # Matrix-vector or Matrix-matrix product
  File "/home/mbaddar/Documents/mbaddar/phd/genmodel/genmodel39_venv/lib/python3.9/site-packages/pykeops/common/lazy_tensor.py", line 1881, in sum
    return self.reduction("Sum", axis=axis, **kwargs)
  File "/home/mbaddar/Documents/mbaddar/phd/genmodel/genmodel39_venv/lib/python3.9/site-packages/pykeops/common/lazy_tensor.py", line 769, in reduction
    return res()
  File "/home/mbaddar/Documents/mbaddar/phd/genmodel/genmodel39_venv/lib/python3.9/site-packages/pykeops/common/lazy_tensor.py", line 951, in __call__
    return self.callfun(*args, *self.variables, **self.kwargs)
  File "/home/mbaddar/Documents/mbaddar/phd/genmodel/genmodel39_venv/lib/python3.9/site-packages/pykeops/torch/generic/generic_red.py", line 626, in __call__
    out = GenredAutograd.apply(
  File "/home/mbaddar/Documents/mbaddar/phd/genmodel/genmodel39_venv/lib/python3.9/site-packages/torch/autograd/function.py", line 539, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/mbaddar/Documents/mbaddar/phd/genmodel/genmodel39_venv/lib/python3.9/site-packages/pykeops/torch/generic/generic_red.py", line 77, in forward
    myconv = keops_binder["nvrtc" if tagCPUGPU else "cpp"](
  File "/home/mbaddar/Documents/mbaddar/phd/genmodel/genmodel39_venv/lib/python3.9/site-packages/keopscore/utils/Cache.py", line 68, in __call__
    obj = self.cls(*args)
  File "/home/mbaddar/Documents/mbaddar/phd/genmodel/genmodel39_venv/lib/python3.9/site-packages/pykeops/common/keops_io/LoadKeOps_nvrtc.py", line 15, in __init__
    super().__init__(*args, fast_init=fast_init)
  File "/home/mbaddar/Documents/mbaddar/phd/genmodel/genmodel39_venv/lib/python3.9/site-packages/pykeops/common/keops_io/LoadKeOps.py", line 18, in __init__
    self.init(*args)
  File "/home/mbaddar/Documents/mbaddar/phd/genmodel/genmodel39_venv/lib/python3.9/site-packages/pykeops/common/keops_io/LoadKeOps.py", line 125, in init
    ) = get_keops_dll(
  File "/home/mbaddar/Documents/mbaddar/phd/genmodel/genmodel39_venv/lib/python3.9/site-packages/keopscore/utils/Cache.py", line 27, in __call__
    self.library[str_id] = self.fun(*args)
  File "/home/mbaddar/Documents/mbaddar/phd/genmodel/genmodel39_venv/lib/python3.9/site-packages/keopscore/get_keops_dll.py", line 110, in get_keops_dll_impl
    map_reduce_obj = map_reduce_class(red_formula_string, aliases, *args)
  File "/home/mbaddar/Documents/mbaddar/phd/genmodel/genmodel39_venv/lib/python3.9/site-packages/keopscore/mapreduce/gpu/GpuReduc1D_ranges.py", line 18, in __init__
    Gpu_link_compile.__init__(self)
  File "/home/mbaddar/Documents/mbaddar/phd/genmodel/genmodel39_venv/lib/python3.9/site-packages/keopscore/binders/nvrtc/Gpu_link_compile.py", line 54, in __init__
    self.my_c_dll = CDLL(jit_compile_dll(), mode=RTLD_LAZY)
  File "/usr/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/mbaddar/.cache/keops2.1.2/Linux_mbaddar-Precision-5540_6.5.0-14-generic_p3.9.18/nvrtc_jit.so: cannot open shared object file: No such file or directory

Process finished with exit code 1
```

And here is some links to help solving the issue
https://github.com/getkeops/keops/issues/318
https://github.com/getkeops/keops/issues/236

**Comment by mbaddar1** [comment]
Revisit the batched and non-batched Sinkhorn Calc here
https://github.com/dfdazac/wassdistance/blob/master/layers.py#L34 
and our modified impl. here
https://github.com/mbaddar1/denoising-diffusion-pytorch/blob/17-ddpm-sklearn-dataset/stat_dist/layers.py#L49
code snippets
`if x.dim() == 2:
            batch_size = 1
        else:
            batch_size = x.shape[0]
`
---
`        if x.dim() == 2:
            batch_size = 1
        elif x.dim() == 3:
            batch_size = x.shape[0]
        else:
            raise ValueError(f"data dim must be 2 or 3 . x and y shape is B X N X D where B is batch size, "
                             f"N is number of points for each "
                             f"batch and D is the (flattened) dim for each point. "
                             f"Received data ndim = {x.dim()}")`
